### ISSUE TITLE
[FR] Ability to change plans Azure SQL instances subsumed using azure-mssql-db-masb-subsume

### ISSUE THREAD

**Issue by claassen** [pivotal/cloud-service-broker#107]
**Is your feature request related to a problem? Please describe.**
After a database has been subsumed, there is no way that I can see to change the plan to scale up/down the database.

**Describe the solution you'd like**
Open to any possibilities.

**Describe alternatives you've considered**
None

**Priority**
High

**Priority Context**
The ability for teams to change their database service plans like they currently can after using the subsume capability is extremely important.

**Platform** 
Azure

**Applicable Services**
azure-mssql-db-masb-subsume

**Comment by erniebilling** [comment]
You can currently cf update-service service-name -c '{"service_objective":"new objective"}' to change the sku for the server.

The idea of plans for a subsumed service seems confusing - cf create-service just imports the current state. What does it mean to cf create-service subsume small if the service is already large? Should it make it small? 

Is it sufficient to allow changing specific parameters? Or would some plans be helpful?

**Comment by claassen** [comment]
Using update-service like that solves the issue. I guess my only concern is that it means users need to be aware of lower level details of the internal fields used rather than just being able to reference plan names.

**Comment by claassen** [comment]
Kind of off topic here but it would be really nice if the standard csb-azure-mssql-db had 'subsume' plan, then once an instance has been subsumed it could be treated just like a regular instance supporting updates by plan name.

E.g.

cf create-service csb-azure-mssql-db subsume my-instance-name -c {'params required for subsuming...'}

then:

cf update-service my-instance-name -p StandardS1

**Comment by claassen** [comment]
Closing this issue for now.
