### ISSUE TITLE
[FR] "examples" parameter blocks should be able to refer to environment variables

### ISSUE THREAD

**Issue by mogul** [pivotal/cloud-service-broker#108]
**Is your feature request related to a problem?  Please describe.**

Some services require security-sensitive parameters to be provided during provisioning or binding. However, I can't put security-sensitive parameters in the `examples` block of the YAML for my brokerpak, as doing so would result in those parameters appearing either in version control or generated docs. Since I can't change the parameters used for examples without rebuilding, I'm unable to make use of `run-tests`. This makes automated testing very difficult, and iterating on a brokerpak very cumbersome.

**Describe the solution you'd like**

I would like to be able to refer to environment variables for both the provisioning and binding parameters in the examples block. Then I want `run-tests` to use the local value of those environment variables when making client requests to the running broker, and `serve-docs` to just list the unexpanded variable names.

**Describe alternatives you've considered**

I've considered working around this by explicitly listing out the testing steps in a Makefile, but this feels like building additional scaffolding for little value. It also reduces the "self-contained, single-source-of-truth" benefit of using the `examples` block.

**Additional Context**

In the brokerpak I'm working on, provisioning requires the user to provide [valid client credentials for an available kubernetes cluster](https://github.com/GSA/datagov-brokerpak/pull/1/commits/a1c5cf18a50e164a3a8699390270618752b88e7b); these cannot and should not be included in the YAML file, so I've had to remove the examples block.

I asked about this situation [in Slack](https://cloudfoundry.slack.com/archives/C0164KKEZGX/p1601342943009100):

> > Hey CSB folks... Is there a way to specify `provision_params` values for `examples:` such that the values will be grabbed from an environment variable? In particular, I have an example I want to use with `run-tests` that refers to a fixture k8s deployment, and I don't want the actual credentials for the fixture k8s to be included in the `.yml` file or in the generated documentation.

> At this time, there is no support for examples to reference environment variables.

**Priority**

Medium

**Priority Context**

While the lack of this feature doesn't prevent use of the broker or development of new brokerpaks, it adds friction to the development process that increases the effort needed to see changes successfully reflected in the broker. In other words, it kills iteration speed.

**Platform** 

Local, but applies to any platform

**Applicable Services**

This is for my own custom brokerpak

**Comment by mogul** [comment]
A possible workaround: It appears that the `client run-examples` command accepts some parameters:
```
$ cloud-service-broker client run-examples --help
Run all examples generated by the use command through a
        provision/bind/unbind/deprovision cycle.

        Exits with a 0 if all examples were successful, 1 otherwise.

Usage:
  cloud-service-broker client run-examples [flags]

Flags:
      --example-name string   only run examples matching this name
      --filename string       json file that contains list of CompleteServiceExamples
  -h, --help                  help for run-examples
  -j, --jobs int              number of parallel client examples to run concurrently (default 1)
      --service-name string   name of the service to run tests for

Global Flags:
      --config string   Configuration file to be read
```

I suspect I can supply the test parameters using the `--filename` parameter, although there's no documentation about this option or what a `CompleteServiceExamples` might be. (I am guessing it is expecting a YAML block that corresponds to the `examples` block in the service YAML; will report back.)

This needs documentation!

**Comment by omerbensaadon** [comment]
Thanks for including this workaround, we will get some docs around this written!

**Comment by omerbensaadon** [comment]
Hey @mogul, I just opened #115, does that cover this FR or do you feel there would still need to be a cleaner implementation to suit your use-case?

**Comment by mogul** [comment]
Yeah, I think that will work.

I tried to use run-examples with a file and wasn't successful... It doesn't seem to do anything. I haven't looked at the code yet to figure out what I'm doing wrong.
