### ISSUE TITLE
[BUG] csb-masb-mssql-db-subsume issue asking for server

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#118]
## Description
As describe in the https://docs.pivotal.io/cloud-service-broker/1-0/reference.html#azure-mssql-fog-preconfig and https://github.com/pivotal/cloud-service-broker/blob/master/docs/mssql-fog-plans-and-config.md documentation, in order to subsume and gain Control of the Secondary Database Instance in a failover group, we must perform the following:

cf create-service csb-masb-mssql-db-subsume PLAN-NAME SERVICE-INSTANCE-NAME -c '{"azure_db_id":"DATABASE-ID"}' 

When I perform that action, I get a "Service broker error: 1 error(s) occurred: server: server is required".

cf create-service csb-masb-mssql-db-subsume current abfog2-s -c '{"azure_db_id":"sqldb-xxxxxx-xxxxx-server01","azure_db_id":"/subscriptions/xxxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxx/resourceGroups/sqldb-xxxxx-rg/providers/Microsoft.Sql/servers/sqldb-xxxx-xxx-server
01/databases/csb-fog-db-c3c7f60c-f6dd-452b-a232-26955f66f829"}'

Creating service instance abfog2-s in org xxxxxxxxx-org / space dev as admin...
Service broker error: 1 error(s) occurred: server: server is required
FAILED

In order to perform a successfull subsume, I must add the "server" parameter in the -c.

cf create-service csb-masb-mssql-db-subsume current abfog2-s -c '{"server":"sqldb-xxxxxx-xxxxx-server01","azure_db_id":"/subscriptions/xxxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxx/resourceGroups/sqldb-xxxxx-rg/providers/Microsoft.Sql/servers/sqldb-xxxx-xxx-server
01/databases/csb-fog-db-c3c7f60c-f6dd-452b-a232-26955f66f829"}'

In the documentation, I don't see any mentions of the paramater having to be specified to gain control of the secondary database.

I also notice that in the acceptance tests for the https://github.com/pivotal/cloud-service-broker/blob/master/acceptance-tests/azure/cf-test-masb-sql-db-subsume.sh, other parameters seemed to be speficied but it appears to be more in regards of subsumming a MASB database and not the secondary FOG database.

## Expected Behavior
As per the documentation, I shouldn't have to specify the "server" argument when I want to gain control of the secondary database within the original primary foundation FOG.

## Actual Behavior
I must add the "server" parameter in the -c in the parameters.

ex: cf create-service csb-masb-mssql-db-subsume current abfog2-s -c '{"server":"sqldb-xxxxxx-xxxxx-server01","azure_db_id":"/subscriptions/xxxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxx/resourceGroups/sqldb-xxxxx-rg/providers/Microsoft.Sql/servers/sqldb-xxxx-xxx-server
01/databases/csb-fog-db-c3c7f60c-f6dd-452b-a232-26955f66f829"}'

## Possible Fix
Update documentation or resolve issue so that we do not have to specify the server.

## Steps to Reproduce

1. Added the json informaiton in the "Existing SQL Server Credentials" - Azure SQL Config To Subsume MASB DB Instances (csb-masb-mssql-db-subsume) portion of the tile.
2. Created a csb-azure-mssql-db-failover-group instance
3. Tried to subsume to gain control of the secondary database of my FOG on the primary foundation.

## Context
Creating end user documentation and test cases and notice this difference compared to previous versions of the tile.

## Your Environment

* Version used: Cloud service broker for Microsoft Azure ver 1.0.1
* Operating System and version (desktop): linux
* Platform (Azure/AWS/GCP): Azure
* Applicable Services: csb-masb-mssql-db-subsume

**Comment by drebake** [comment]
When I try to delete that service now, I get the following error.

dma7217:~/ $ cf service abfog2-s                                                                                                                                                                                                                                      [8:33:43]
Showing info of service abfog2-s in org xxxxxxxxxxxx-org / space dev as admin...

name:             abfog2-s
service:          csb-masb-mssql-db-subsume
tags:
plan:             current
description:      Subsume control of existing MASB created SQL database
documentation:    https://docs.microsoft.com/en-us/azure/sql-database/
dashboard:
service broker:   cloud-service-broker-azure

Showing status of last operation from service abfog2-s...

status:    delete failed
message:   Error: Sql Server "sqldb-cfzcca-xxxxxxx-server01" was not found in Resource Group "sqldb-cfzcea-rg"  on data.tf line 2, in data "azurerm_sql_server" "azure_sql_db_server":   2: data "azurerm_sql_server" "azure_sql_db_server" { exit status 1
started:   2020-10-23T12:31:34Z
updated:   2020-10-23T12:32:36Z

There are no bound apps for this service.

Upgrades are not supported by this broker.

-----------------------------------------

**Comment by erniebilling** [comment]
We made a change to the masb subsume service to be configured like the csb-azure-mssql-db service (use database credentials configured by operator) which has broken this functionality. We will re-visit this issue.

**Comment by drebake** [comment]
Should I have simply used the csb-azure-mssql-db-subsume and not the csb-masb-mssql-db-subsume to gain control of the secondary database in the failover group?

**Comment by omerbensaadon** [comment]
Am i right in thinking this bug is currently blocked by https://github.com/terraform-providers/terraform-provider-azurerm/issues/8892

**Comment by drebake** [comment]
I think that resolving that bug would void the need of using the subsume in this case to gain access to the secondary database on the secondary site but originally the subsume was a work around for that issue but appears to be broken now.

**Comment by omerbensaadon** [comment]
this goes away thanks to fix (see #105).
