### ISSUE TITLE
[FR]Improve legacy broker migration with additional properties for AWS RDS PostegreSQL plans

### ISSUE THREAD

**Issue by sbogar-shs** [pivotal/cloud-service-broker#139]
In order to better facilitate the migration from the legacy broker, a few additional properties would be beneficial

The following additional properties from the Legacy broker would allow for a cleaner migration of Legacy plans:

Enable Storage Encryption
DB Parameter Group Name
DB Subnet Group Name 
Require SSL for communication
VPC Security Group Ids

This will allow customers to migrate using the same networking, parameter, and security groups that already exist from the Legacy Broker.

**Comment by omerbensaadon** [comment]
Partially resolved by #142 (thanks again @michaelmccaskill) team still has some work to do here, but it is in flight!

**Comment by erniebilling** [comment]
Released new version with these enhancements, please let us know if it works for you @sbogar-shs
