### ISSUE TITLE
[FR] Add vnet integration for Azure Redis Cache Premium plans

### ISSUE THREAD

**Issue by thanhdesjardins** [pivotal/cloud-service-broker#146]
**Is your feature request related to a problem? Please describe.**
By default, all the communication through Azure redis Cache are done via Internet. It would be good that all the communication stay in the vnet.

**Describe the solution you'd like**
The azure terraform provider already has an option allowing to specify in which subnet the Redis instance will be. 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache#subnet_id
We would like the option to be present in the CSB tile.

**Describe alternatives you've considered**
Add the code in the CSB tile allowing to specify in which subnet the redis instance will be

**Priority**
High (for security)

**Priority Context**
To enhance security

**Platform** 
Azure

**Applicable Services**

**Comment by thanhdesjardins** [comment]
I was thinking of this solution:

In file https://github.com/pivotal/cloud-service-broker/blob/master/azure-brokerpak/azure-redis.yml:
Add the field:

`- field_name: subnet_id
  type: string
  details: The subnet in which the redis instance will be created (only for premium plan)
  default: ""`


In file https://github.com/pivotal/cloud-service-broker/blob/master/azure-brokerpak/terraform/azure-redis/redis-provision.tf
Add the parameter:

`variable subnet_id { type = string }`

`resource "azurerm_redis_cache" "redis" {
  depends_on = [ azurerm_resource_group.azure-redis ]  
  name                = var.instance_name
  sku_name            = var.sku_name
  family              = var.family
  capacity            = var.capacity
  location            = var.location
  **subnet_id          = length(var.subnet_id) == 0 ? "" : var.subnet_id**
  resource_group_name = local.resource_group
  minimum_tls_version = length(var.tls_min_version) == 0 ? "1.2" : var.tls_min_version
  tags                = var.labels
  redis_configuration {
    maxmemory_policy   = length(var.maxmemory_policy) == 0 ? "allkeys-lru" : var.maxmemory_policy
  }
}
`

**Comment by drebake** [comment]
@omerbensaadon , we're currently working on including this feature and will provide a PR shortly for your review.

**Comment by omerbensaadon** [comment]
Awesome!!

Thank you so much Andre

**Comment by thanhdesjardins** [comment]
@omerbensaadon : Hello, we just provided the PR for you.

**Comment by omerbensaadon** [comment]
fixed as part of [v0.8.3](https://github.com/pivotal/cloud-service-broker/releases/tag/v0.8.3-beta)!
