### ISSUE TITLE
[BUG] Execute permission denied on stored procedures after Azure SQL subsume

### ISSUE THREAD

**Issue by claassen** [pivotal/cloud-service-broker#151]
## Description
After subsuming an Azure SQL database, the new service credentials do not have permission to execute stores procedures that were created before the subsume process.

## Expected Behavior
Existing stored procedures should be executable by the new service credentials created after subsume.

## Actual Behavior
Receive errors like:

```
"Microsoft.Data.SqlClient.SqlException (0x80131904): The EXECUTE permission was denied on the object 'SP_GetMultipleRates', database 'rates-db-dev', schema 'dbo'."
```

when code tries to execute stored procedures after subsume.

## Possible Fix
?

## Steps to Reproduce
1. Subsume database that has stored procedures
2. Try to execute stored procedure using new service credentials

## Context
This is major issue for teams as their apps are not functioning after their database has been subsumed.

## Your Environment
* Version used: sb-0.2.1-rc.1-azure-1.0.0-rc.21
* Platform (Azure/AWS/GCP): Azure
* Applicable Services: csb-azure-mssql-db, csb-azure-mssql-db-failover-group

**Comment by erniebilling** [comment]
A new sql login is created when the app is bound to the subsumed instance, it is granted the following roles:
```
db_ddladmin
db_datareader
db_datawriter
```
Is there a role that needs to be added to allow stored procedure execution?

**Comment by claassen** [comment]
I think it needs EXEC permission. I have a PR I will submit shortly for review

**Comment by claassen** [comment]
https://github.com/pivotal/cloud-service-broker/pull/154
