### ISSUE TITLE
[BUG] Credentials are output in plain text in application console logs

### ISSUE THREAD

**Issue by tommyforlini** [pivotal/cloud-service-broker#156]
## Description
After deploying the broker to our environment and reviewing the output logs, all of the credentials used to provision services are logged. 

## Expected Behavior
When credentials are logged, they should either be masked OR omitted from the output.

## Actual Behavior
The credentials are displayed in plaintext. Example for  csb-azure-mssql-db you will find in the logs admin_username and admin_password in plaintext.

## Possible Fix
Ultimately fixing the leaked credentials would be the preferable solution but based on the code, I see that a struct attribute `data` of type interface{} just outputs whatever is inside it. It's probably normal since this was most likely intended to be a generic placeholder for any information relevant to a supported terraform service (azure mssql, azure mysql, azure cosmosdb, etc etc)
ELSE   
In `utils.go` I found this logger init function which maybe the culprit. If the logger levels could be externalized to os.Getenv(), this can maybe be leveraged at deployment/startup time to bump up the levels to INFO, ERROR, FATAL 
```
func NewLogger(name string) lager.Logger {
	logger := lager.NewLogger(name)

	logger.RegisterSink(lager.NewWriterSink(os.Stderr, lager.ERROR))
	logger.RegisterSink(lager.NewWriterSink(os.Stdout, lager.DEBUG))

	return logger
}
``` 
changed to something like this....
```
func NewLogger(name string) lager.Logger {
	logger := lager.NewLogger(name)

        logLevel := os.Getenv("LOG_LEVEL") 
        if len(logLevel) < 1 {
            logLevel = lager.DEBUG
        }
        
	logger.RegisterSink(lager.NewWriterSink(os.Stderr, lager.ERROR))
	logger.RegisterSink(lager.NewWriterSink(os.Stdout, logLevel))

	return logger
}
```

## Steps to Reproduce
1. deploy broker
2. make a request to provision an Azure Sql Database
3. inspect logs and you will find admin_username and admin_password in plain text

## Context
This is going to be huge security risk for all non-sandbox environments

## Your Environment
* Version used: sb-0.2.1-rc.1-azure-1.0.0-rc.21
The * Platform (Azure/AWS/GCP): Azure
* Applicable Services: csb-azure-mssql-db

**Comment by omerbensaadon** [comment]
We're on it!! Thank you for submitting this

**Comment by tommyforlini** [comment]
Upon further testing in our environment, it seems the leak is only coming from `csb-azure-mssql-db` and NOT `csb-azure-mysql`. Ive updated the issue
