### ISSUE TITLE
[FR] Service to bind to existing AzureSQL failover group in a different PCF foundation

### ISSUE THREAD

**Issue by claassen** [pivotal/cloud-service-broker#41]
**Is your feature request related to a problem? Please describe.**
When we create an AzureSQL failover group, with e.g.:

cf create-service csb-azure-mssql-db-failover-group small my-failover-group -c '{"server_pair": "pair1", "instance_name": "csb-failover-group-test", "db_name": "csb-db-test"}'

there is no way to bind to this existing failover group from a different PCF org/space which is required if we want an app that is deployed in a different DR region to be able to connect to and use the existing failover group.

**Describe the solution you'd like**
Something like:

cf create-service csb-azure-mssql-db-failover-group-existing small my-failover-group -c '{"server_pair": "pair1", "instance_name": "csb-failover-group-test"}'

which would create a service which provides connection details to the existing failover group.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Platform** 
PCF

**Applicable Services**
Azure SQL

**Comment by omerbensaadon** [comment]
Thanks @claassen, I'll make sure this gets discussed at tomorrow's standup and allocated on our Projects board!

**Comment by tanjoht** [comment]
There isn't a terraform data source for the mssql fog so there doesn't appear to be a clean way to do this. One possible solution is to "simulate" this resource by outputting the exact same parameters/envs that a normal failover group would provide. The only difference is that the user will enter the fog db_name and fog instance_name as inputs which they can obtain from the environment variables of the service instance on the primary site. This would be equivalent to a user just copying the env variables for the fog service instance on the primary site and then adding it to all the apps on their dr side.

The broker tf file can potentially look like this:
locals {
  serverFQDN = format("%s.database.windows.net", var.instance_name)
}

output "sqldbName" {value = var.db_name}
output "sqlServerName" {value = var.instance_name}
output "sqlServerFullyQualifiedDomainName" {value = local.serverFQDN}
output "hostname" {value = local.serverFQDN}
output "port" {value = 1433}
output "name" {value = var.db_name}
output "username" {value = var.server_credential_pairs[var.server_pair].admin_username}
output "password" {value = var.server_credential_pairs[var.server_pair].admin_password}

Using the azure-mssql-db-failover.yml as a template for the service definition, altering the "provisioning" code block to require the 2 additional inputs above, will maintain the service key binding functionality as well.

Provisioning the instance would look something like: cf create-service csb-azure-mssql-db-failover-group-dr standard csb-test-fog-dr2 -c '{"server_pair":"pair1","db_name":"csb-fog-db","instance_name":"csb-azsql-fog"}'

The plan will then create a new db user/password under that existing fog. 


Again, not as clean as extending the azure tf provider to include a data source for a mssql fog but this method appears to work for this use case.

**Comment by erniebilling** [comment]
@tanjoht That's about the track we're on as well, working on it presently.

I have a question - is it safe to assume the two PAS foundations in the two Azure locations share at least the same Azure tenant? Want to make sure there are no network/firewall issues to take into account.

**Comment by tanjoht** [comment]
Yes i think it's safe to assume its the same azure tenant - at least that's what it is in our case.

**Comment by erniebilling** [comment]
Perfect @tanjoht, thanks.

@claassen Question for you regarding UX. Your example shows a new service (csb-azure-mssql-db-failover-group-existing) for connecting to an existing fail over group. Another option would be to add a new plan to the existing service (csb-azure-mssql-db-failover-group) so the experience could be something like:

**In Primary Foundation**
`cf create-service csb-azure-mssql-db-failover-group small my-failover-group -c '{"server_pair": "pair1", "instance_name": "csb-failover-group-test", "db_name":"test-db"}'
`
**In Secondary Foundation**
`cf create-service csb-azure-mssql-db-failover-group existing my-failover-group -c '{"server_pair": "pair1", "instance_name": "csb-failover-group-test", "db_name":"test-db"}'
`

Any preference here?

**Comment by claassen** [comment]
No strong preference, although I like that 'existing' plan idea.

**Comment by omerbensaadon** [comment]
@claassen @tanjoht please let us know if this works as expected! Would love some feedback.

**Comment by drebake** [comment]
I can confirm that I tested this new FR and it's working properly.

I will open a bug in order to fix the documentation in order to include the "instance_name" and "db_name" in the Secondary Foncdation create request.
