### ISSUE TITLE
[BUG] When deleting a csb-azure-mssql-db-failover-group, the database read-only database on the secondary server is not deleted.

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#46]
## Description
When deleting a csb-azure-mssql-db-failover-group, the database read-only database on the secondary site is not deleted.

The failover-group is deleted on both servers in the server "pair", but the database appears to only be deleted on the primairy server and remains on the secondary failover-group server.

## Expected Behavior
When deleting a failovergroup, the failovergroup and databases are deleted on both servers that are configured in the "pair"

## Actual Behavior
A manual cleanup is required for the database on the secondary server.

## Possible Fix
Delete all database instances in the server "pair".

## Steps to Reproduce
1. Provision a new csb-azure-mssql-failover-db
cf create-service csb-azure-mssql-db-failover-group small db-fog-small -c '{"server_pair":"pair1"}'

2. Get the guid of the service
cf service db-fog-small --guid

3. Delete the csb-azure-mssql-db-failover-group.
cf ds db-fog-small

4. Got on the secondary server of the server "pair" and the database will still be present.

## Context
Manual cleanup required after deleteing the service.

## Your Environment
* Version used: Bosh 2.9.6, TAS 2.9.7, cf version 6.51.0+2acd15650.2020-04-07, azure-services-0.0.1-rc.97.brokerpak
* Operating System and version (desktop): elementary OS 5.1.6 Hera
* Link to your project (if public):
* Platform (Azure/AWS/GCP): Azure
* Applicable Services: csb-azure-mssql-db-failover-group

**Comment by erniebilling** [comment]
Opened issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/7938 as this seems to be a shortcoming in the terraform provider.

**Comment by erniebilling** [comment]
Getting in contact with Microsoft to request support for this issue.

**Comment by erniebilling** [comment]
There is a workaround fix for this released now. See https://github.com/pivotal/cloud-service-broker/blob/master/docs/mssql-db-fog-config.md#notes-on-the-secondary-db-created-by-fog

A more comprehensive fix may be implemented in the future.

**Comment by omerbensaadon** [comment]
@drebake let me know if this resolves the issue for you!

**Comment by drebake** [comment]
It appears to work. If we create a secondary service using the csb-masb-mssql-db-subsume service, once we delete it, it removes the secondary database.

We then delete the original csb-azure-mssql-db-failover-group service and it delete the failover-group and the original database.

Steps:
1- cf create-service csb-azure-mssql-db-failover-group standard-S0 fog1 -c '{"server_pair":"pair1"}'
2- cf service fog1
3- cf create-service csb-masb-mssql-db-subsume current secondary-db -c '{"azure_db_id":"/subscriptions/XXXXXXXXXXXX-4140-8c5c-XXXXXXXXXX/resourceGroups/sqldb-cfzcea-rg/providers/Microsoft.Sql/servers/sqldb-cfzcea-csb-server01/databases/csb-fog-db-XXXXXXXX-XXXXX-XXXX-XXXX-XXXXXXXXXXXa2"}'
4- cf ds secondary-db
5- cf ds fog1

Is this the intended way to use the subsume to delete the secondary service?

**Comment by omerbensaadon** [comment]
Yup, that's right @drebake
