### ISSUE TITLE
[FR] Updating csb-azure-mssql-db and csb-azure-mssql-db-failover-group not supported by broker

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#47]
**Is your feature request related to a problem? Please describe.**
In the cloud-service-broker, we are enable to run the update-service in order to update the service to a bigger plan as it was available with the MASB.

If we try to perform a "cf update-server csb-db -p bigger-plan" we get the following error.
Server error, status code: 400, error code: 11004, message: The service does not support changing plans."

**Describe the solution you'd like**
We would like to be able to increase the database plan in order to update to a bigger plan is plan quotas are reach.

**Describe alternatives you've considered**
The alternative is to create a new service and perform a migration from the original DB to a new database.

**Additional context**
![image](https://user-images.githubusercontent.com/47528848/87578399-5b7ad680-c6a2-11ea-9465-2e8e1510df8a.png)

**Platform** 
Azure

Version used: Bosh 2.9.6, TAS 2.9.7, cf version 6.51.0+2acd15650.2020-04-07, azure-services-0.0.1-rc.97.brokerpak

**Applicable Services**
csb-azure-mssql-db and csb-azure-mssql-db-failover-group

**Comment by erniebilling** [comment]
Just want to capture one gotcha here, there are parameters that may result in Azure creating new service instance (instead of updating an existing service instance.) Story needs to include ability to mark parameters that can't be updated.

**Comment by omerbensaadon** [comment]
hey @drebake we are on the verge of pushing this feature. 

One small caveat: we haven't applied filtering to this command yet, so you can update some pretty "dangerous" parameters by using the `-c` flag. 

Just a heads up, the CSB will (for now) let you do that and probably cause some pain. i.e. if you try and change the location from east -> west it will result in a new instance being created and you will lose your data. 

Stick with `cf update -p` for now, we will implement filtering as apart of a follow-on story to make the limitations a bit safer. 

With great power comes great responsibility. 🧙🏼‍♂️

**Comment by drebake** [comment]
@omerbensaadon  Thank you for that information. 

We are simply looking at doing the update-service with the -p in order to change the plan. We are not looking to change any other settings with the -c flag at this time.

I did install the latest *-113 brokerpak and tested the plan update. It worked fine for the csb-azure-mssql-db but fails for the csb-azure-mssql-db-failover-group.

**Comment by erniebilling** [comment]
@drebake Can you share the failure message you get?

**Comment by drebake** [comment]
Getting services in org transfodev-org / space azbroker as admin...

name            service                             plan          bound apps             last operation     broker                   upgrade available
csb-sql         p.mysql                             db-small      cloud-service-broker   update succeeded   dedicated-mysql-broker   no
fog-S0-update   csb-azure-mssql-db-failover-group   standard-S0   spring-music           update succeeded   cloud-service-broker     
dma7217@abvmlnx:cfzcca~$cf update-service fog-S0-update -p standard-S3
Updating service instance fog-S0-update as admin...
OK

Update in progress. Use 'cf services' or 'cf service fog-S0-update' to check operation status.
dma7217@abvmlnx:cfzcca~$watch cf s
dma7217@abvmlnx:cfzcca~$cf s
Getting services in org transfodev-org / space azbroker as admin...

name            service                             plan          bound apps             last operation     broker                   upgrade available
csb-sql         p.mysql                             db-small      cloud-service-broker   update succeeded   dedicated-mysql-broker   no
fog-S0-update   csb-azure-mssql-db-failover-group   standard-S0   spring-music           update failed      cloud-service-broker     
dma7217@abvmlnx:cfzcca~$


`   2020-08-03T16:03:30.75-0400 [APP/PROC/WEB/0] OUT {"timestamp":"1596485010.758543730","source":"terraform@/home/vcap/tmp/gsb320482012","message":"terraform@/home/vcap/tmp/gsb320482012.results","log_level":1,"data":{"error":{"Stderr":null},"errors":"\nError: Invalid index\n\n  on brokertemplate/definition.tf line 45, in data \"azurerm_sql_server\" \"primary_sql_db_server\":\n  45:   name                         = var.server_credential_pairs[var.server_pair].primary.server_name\n    |----------------\n    | var.server_credential_pairs is map of object with 1 element\n    | var.server_pair is null\n\nCan't use a null value as an indexing key.\n\n\nError: Invalid index\n\n  on brokertemplate/definition.tf line 46, in data \"azurerm_sql_server\" \"primary_sql_db_server\":\n  46:   resource_group_name          = var.server_credential_pairs[var.server_pair].primary.resource_group\n    |----------------\n    | var.server_credential_pairs is map of object with 1 element\n    | var.server_pair is null\n\nCan't use a null value as an indexing key.\n\n\nError: Invalid index\n\n  on brokertemplate/definition.tf line 50, in data \"azurerm_sql_server\" \"secondary_sql_db_server\":\n  50:   name                         = var.server_credential_pairs[var.server_pair].secondary.server_name\n    |----------------\n    | var.server_credential_pairs is map of object with 1 element\n    | var.server_pair is null\n\nCan't use a null value as an indexing key.\n\n\nError: Invalid index\n\n  on brokertemplate/definition.tf line 51, in data \"azurerm_sql_server\" \"secondary_sql_db_server\":\n  51:   resource_group_name          = var.server_credential_pairs[var.server_pair].secondary.resource_group\n    |----------------\n    | var.server_credential_pairs is map of object with 1 element\n    | var.server_pair is null\n\nCan't use a null value as an indexing key.\n\n\nError: Invalid index\n\n  on brokertemplate/definition.tf line 104, in output \"username\":\n 104: output \"username\" {value = var.server_credential_pairs[var.server_pair].admin_username}\n    |----------------\n    | var.server_credential_pairs is map of object with 1 element\n    | var.server_pair is null\n\nCan't use a null value as an indexing key.\n\n\nError: Invalid index\n\n  on brokertemplate/definition.tf line 105, in output \"password\":\n 105: output \"password\" {value = var.server_credential_pairs[var.server_pair].admin_password}\n    |----------------\n    | var.server_credential_pairs is map of object with 1 element\n    | var.server_pair is null\n\nCan't use a null value as an indexing key.\n\n","output":""}}


   2020-08-03T16:04:28.44-0400 [APP/PROC/WEB/0] OUT {"timestamp":"1596485068.443503618","source":"cloud-service-broker","message":"cloud-service-broker.lastOperation.starting-check-for-operation","log_level":1,"data":{"instance-id":"adcfb3b4-eb6c-4da3-aab0-6aef2026a43c","session":"12"}}
   2020-08-03T16:04:28.44-0400 [APP/PROC/WEB/0] OUT {"timestamp":"1596485068.443590164","source":"cloud-service-broker","message":"cloud-service-broker.Last Operation","log_level":1,"data":{"instance_id":"adcfb3b4-eb6c-4da3-aab0-6aef2026a43c","operation_data":"tf:adcfb3b4-eb6c-4da3-aab0-6aef2026a43c:","plan_id":"881de5d9-e078-44e7-bed5-26faadabda3c","service_id":"d7ba0e8e-4480-4543-a504-b57e1dd1f1ad"}}
   2020-08-03T16:04:28.45-0400 [APP/PROC/WEB/0] OUT {"timestamp":"1596485068.449896812","source":"cloud-service-broker","message":"cloud-service-broker.lastOperation.done-check-for-operation","log_level":1,"data":{"instance-id":"adcfb3b4-eb6c-4da3-aab0-6aef2026a43c","session":"12","state":"failed"}}
   2020-08-03T16:04:28.45-0400 [RTR/0] OUT cloud-service-broker-restless-jaguar-sz.apps.cfzcca.dev.xxxxxxxxxxxxxxxx.com - [2020-08-03T20:04:28.444587894Z] "GET /v2/service_instances/adcfb3b4-eb6c-4da3-aab0-6aef2026a43c/last_operation?operation=tf%3Aadcfb3b4-eb6c-4da3-aab0-6aef2026a43c%3A&plan_id=881de5d9-e078-44e7-bed5-26faadabda3c&service_id=d7ba0e8e-4480-4543-a504-b57e1dd1f1ad HTTP/1.1" 200 0 2262 "-" "HTTPClient/1.0 (2.8.3, ruby 2.5.5 (2019-03-15))" "10.XXX.XX.XX:54042" "10.XXX.XX.XX:61054" x_forwarded_for:"10.XXX.XX.XX" x_forwarded_proto:"https" vcap_request_id:"09f35366-d82e-486e-5d59-fb02525c8a89" response_time:0.008858 gorouter_time:0.000142 app_id:"bf0913bb-5aef-4cdc-a02d-f0dd98b4d059" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"d17fd652cfe8bb85" x_b3_spanid:"d17fd652cfe8bb85" x_b3_parentspanid:"-" b3:"d17fd652cfe8bb85-d17fd652cfe8bb85"
   2020-08-03T16:04:28.45-0400 [RTR/0] OUT `

**Comment by erniebilling** [comment]
@drebake You will need to include the server_pair name you used at provision time:

`cf update-service fog-S0-update -p standard-S3 -c '{"server_pair":"pair_xxx"}'`

Typically anything provided with -c at `cf create-service` will also have to be provided at `cf update-service`

**Comment by drebake** [comment]
@erniebilling  Sorry about that.... I was trying to avoid the -c flag so badly that I forgot the server_pair.

I just did another test with the server_pair.

The cf command came up successfull, the primary database got updated but not the secondary database on the secondary server.

**Comment by erniebilling** [comment]
@drebake Thanks for the update. I guess I'm not surprised by that. The azure terraform provider doesn't seem to handle the secondary server well at all (not deleting the database upon destroy and now not reflecting the sku upon update.) I'll add this to the story.

**Comment by erniebilling** [comment]
Gonna close this issue since the service now supports update. The failure to propagate to secondary database is captured in #63
