### ISSUE TITLE
[DOCS] MASB "azure-sqldb-failover-group / ExistingDatabaseInFailoverGroup" equivalence.

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#48]
## Documentation Requested 
I would like to know if there is a way that we can connect to a csb-azure-mssql-db-failover-group secondary database from another PCF platform.

Basicly the equivalence of the MASB "azure-sqldb-failover-group / ExistingDatabaseInFailoverGroup" service enabled us to create a service-instance on another PCF platform on another site in order to connect to the FOG from the secondary server.

What would be the equivalence of the MASB "azure-sqldb-failover-group / ExistingDatabaseInFailoverGroup" option using the cloud-service-broker?

Thank you

**Comment by drebake** [comment]
I've just noticed that the documentation for the "existing plan" was added to the "Microsoft Azure SQL Failover Group Config" yesterday.
(https://github.com/pivotal/cloud-service-broker/commit/a8de3df6275d1411abf3a7373ae2a2b73ba0a9f5)

That's exactly what I was looking for. I'll make sure i've got the latest brokerpacs and try it.

**Comment by omerbensaadon** [comment]
@drebake if you feel that documentation is sufficient, feel free to close this issue 👍
