### ISSUE TITLE
[BUG] Broker database name can't be set, even to default

### ISSUE THREAD

**Issue by mogul** [pivotal/cloud-service-broker#49]
## Description
The broker does not pick up the name of the database to use from `VCAP_SERVICES`, the `DB_NAME` env var, or the default in the source code.

## Expected Behavior
GIVEN I have authenticated with `cf login -a api.fr.cloud.gov -sso`
AND I have run `cf create-service aws-rds medium-mysql servicebroker-db -t mysql` 
AND I have run `cf push cloud-service-broker -c './cloud-service-broker serve --config config.yml' -b binary_buildpack --random-route --no-start` 
AND I have run `cf bind-service cloud-service-broker servicebroker-db` to bind the brokered MySQL service to the broker
AND the `VCAP_SERVICES` variable in `cf env cloud-service-broker` looks like:
```
VCAP_SERVICES=
{
  "aws-rds": [
    {
      "label": "aws-rds",
      "provider": null,
      "plan": "medium-mysql",
      "name": "servicebroker-db",
      "tags": [
        "database",
        "RDS",
        "mysql"
      ],
      "instance_name": "servicebroker-db",
      "binding_name": null,
      "credentials": {
        "db_name": "cgawsbrokerprodk8evyj9pv9fdotd",
        "host": "cg-aws-broker-prodk8evyj9pv9fdotd.ci7nkegdizyy.us-gov-west-1.rds.amazonaws.com",
        "password": "[REDACTED]",
        "port": "3306",
        "uri": "mysql://ux6uzfrqb2f61kei:[REDACTED]@cg-aws-broker-prodk8evyj9pv9fdotd.ci7nkegdizyy.us-gov-west-1.rds.amazonaws.com:3306/cgawsbrokerprodk8evyj9pv9fdotd",
        "username": "ux6uzfrqb2f61kei"
      },
      "syslog_drain_url": null,
      "volume_mounts": []
    }
  ]
}
```
WHEN I run `cf start cloud-service-broker`
THEN I should see the `cloud-service-broker` app start successfully 

## Actual Behavior
BUT I see 
```
Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs cloud-service-broker --recent' for more information
FAILED
```
AND I see in the app logs
```
23:29:29.781: [APP/PROC/WEB.0] {"timestamp":"1594880969.781164885","source":"cloud-service-broker","message":"cloud-service-broker.Connecting to MySQL Database","log_level":1,<b>"data":{"host":"cg-aws-broker-prodk8evyj9pv9fdotd.ci7nkegdizyy.us-gov-west-1.rds.amazonaws.com","name":"","port":"3306"}}
23:29:29.801: [APP/PROC/WEB.0] (Error 1046: No database selected) 
23:29:29.801: [APP/PROC/WEB.0] [2020-07-16 06:29:29]  
23:29:29.804: [APP/PROC/WEB.0] (Error 1046: No database selected) 
23:29:29.804: [APP/PROC/WEB.0] [2020-07-16 06:29:29]  
23:29:29.806: [APP/PROC/WEB.0] (Error 1046: No database selected) 
23:29:29.806: [APP/PROC/WEB.0] [2020-07-16 06:29:29]  
23:29:29.810: [APP/PROC/WEB.0] (Error 1046: No database selected) 
23:29:29.810: [APP/PROC/WEB.0] [2020-07-16 06:29:29]  
23:29:29.813: [APP/PROC/WEB.0] panic: Error migrating database: Error 1046: No database selected
23:29:29.813: [APP/PROC/WEB.0] goroutine 1 [running]:
23:29:29.813: [APP/PROC/WEB.0] github.com/pivotal/cloud-service-broker/db_service.New.func1()
23:29:29.813: [APP/PROC/WEB.0] 	/tmp/build/80754af9/cloud-service-broker/db_service/db_service.go:37 +0x123
23:29:29.813: [APP/PROC/WEB.0] sync.(*Once).doSlow(0x1bd6ef8, 0xc00063fbe8)
23:29:29.813: [APP/PROC/WEB.0] 	/usr/local/go/src/sync/once.go:66 +0xec
23:29:29.813: [APP/PROC/WEB.0] sync.(*Once).Do(...)
23:29:29.813: [APP/PROC/WEB.0] 	/usr/local/go/src/sync/once.go:57
23:29:29.813: [APP/PROC/WEB.0] github.com/pivotal/cloud-service-broker/db_service.New(0x1409380, 0xc0006945a0, 0x1409380)
23:29:29.814: [APP/PROC/WEB.0] 	/tmp/build/80754af9/cloud-service-broker/db_service/db_service.go:34 +0x88
23:29:29.814: [APP/PROC/WEB.0] github.com/pivotal/cloud-service-broker/cmd.serve()
23:29:29.814: [APP/PROC/WEB.0] 	/tmp/build/80754af9/cloud-service-broker/cmd/serve.go:71 +0x70
23:29:29.814: [APP/PROC/WEB.0] github.com/pivotal/cloud-service-broker/cmd.init.5.func1(0xc0001e9180, 0xc000680fe0, 0x0, 0x2)
23:29:29.814: [APP/PROC/WEB.0] 	/tmp/build/80754af9/cloud-service-broker/cmd/serve.go:52 +0x20
23:29:29.814: [APP/PROC/WEB.0] github.com/spf13/cobra.(*Command).execute(0xc0001e9180, 0xc000680fc0, 0x2, 0x2, 0xc0001e9180, 0xc000680fc0)
23:29:29.814: [APP/PROC/WEB.0] 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x29d
23:29:29.814: [APP/PROC/WEB.0] github.com/spf13/cobra.(*Command).ExecuteC(0x1b9e9e0, 0x44299a, 0x1b32760, 0xc00005a778)
23:29:29.814: [APP/PROC/WEB.0] 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
23:29:29.814: [APP/PROC/WEB.0] github.com/spf13/cobra.(*Command).Execute(...)
23:29:29.814: [APP/PROC/WEB.0] 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
23:29:29.814: [APP/PROC/WEB.0] github.com/pivotal/cloud-service-broker/cmd.Execute()
23:29:29.814: [APP/PROC/WEB.0] 	/tmp/build/80754af9/cloud-service-broker/cmd/root.go:43 +0x31
23:29:29.814: [APP/PROC/WEB.0] main.main()
23:29:29.814: [APP/PROC/WEB.0] 	/tmp/build/80754af9/cloud-service-broker/main.go:22 +0x20
23:29:29.856: [APP/PROC/WEB.0] Exit status 2
```

## Possible Fix
The code is somehow coming up with  `"name":""` (the empty string) for the database name instead of either using [the `servicebroker` default value](https://github.com/pivotal/cloud-service-broker/blob/7daed67576d5b8877356d7f187f46eb216406ed1/db_service/setup_db.go#L58) or the `db_name` from `VCAP_SERVICES`.

I also tried setting `db.name` in the `config.yml` file, re-pushing, and then `cf restart`'ing the app, but found the same thing happened.

I also tried also setting the DB_NAME env var with `cf set-env cloud-service-broker DB_NAME cgawsbrokerprodk8evyj9pv9fdotd` and `cf restart cloud-service-broker`, but found the same thing happened.

The fact that none of these work and the name is empty make me think there's a bug somewhere in here, but I haven't the Golang chops to find it.

## Steps to Reproduce

(see GIVEN/WHEN/THEN steps above)

## Context
I'm trying to run the cloud-service-broker successfully in cloud.gov, in preparation for writing my own brokerpak services and contributing them upstream.

## Your Environment
* Version used: https://github.com/pivotal/cloud-service-broker/releases/tag/sb-0.1.0-rc.32-aws-0.0.1-rc.106
* Operating System and version (desktop): OS X High Sierra
* Link to your project (if public): 
* Platform (Azure/AWS/GCP): AWS
* Applicable Services: Any, I can't get the broker to recognize its own MySQL storage

**Comment by omerbensaadon** [comment]
After speaking with @mogul in the #cloudservicebroker-beta channel on CF Slack, we may need to update install documentation if delivering this bug changes the process for installation.

**Comment by mogul** [comment]
I started out by following the instructions from "Step By Step From a Pre-build Release with a Bound MySQL Instance" [here](https://github.com/pivotal/cloud-service-broker/blob/master/docs/aws-installation.md#step-by-step-from-a-pre-build-release-with-a-bound-mysql-instance). When it didn't work, I looked at the other methods and experimented with manually creating a "servicebroker" DB in the bong MySQL instance, setting the config file and environment variable, etc. 

(In other words, the docs were all good, I just wasn't successful when I followed them.)

**Comment by erniebilling** [comment]
Are you using the AWS Labs broker or the Pivotal AWS broker?

The issue seems to be that the credential block has the database name in the `db_name` field. The broker is expecting to find that in the `name` field, like the p.mysql broker provides. And if a VCAP_SERVICES is set, the broker doesn't try to override with other environment variables./

Should be possible to add support to the broker to try both `name` and `db_name` in the credential block to support this broker.

**Comment by mogul** [comment]
Also using the "uri" field if present might be more reliable.

**Comment by erniebilling** [comment]
This is an area where the broker isn't terribly intelligent. If VCAP_SERVICES is there, it just uses them best it can.

A workaround would be to unbind the broker from the RDS instance and instead `cf create-service-key` on the instance, and use the values to `cf set-env` DB_HOST, DB_USERNAME, DB_PASSWORD, and DB_NAME (or set this in a config file.)

**Comment by mogul** [comment]
That was my thought too. I'll do my best to get the cloud.gov team to match the Pivotal and AWS broker's fields for VCAP_SERVICES, but I am not on that team and I know they have a lot of other priorities. Should I expect the behavior here will become a little more resilient to this situation in future, or is it up to me to use the workaround or make it unnecesary?

**Comment by mogul** [comment]
([Example of addressing a similar problem via use of `uri` when present.](https://github.com/cloudfoundry-community/mattermost-cf-integrator/issues/1))

**Comment by omerbensaadon** [comment]
@mogul Hey we are combing through issues, you should expect to have to use a workaround to make this work, we do not plan addressing this issue

**Comment by mogul** [comment]
Understandable, thanks for being explicit.

**Comment by mogul** [comment]
The cloud.gov team accepted [my PR](https://github.com/cloud-gov/aws-broker/pull/97), so everything's good here. Thanks for your patience!
