### ISSUE TITLE
[FR] We would like to be able to configure the "read_write_endpoint_failover_policy"  to manual mode.

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#50]
**Is your feature request related to a problem? Please describe.**
We would like to be able to configure the "read_write_endpoint_failover_policy"  to manual mode. Currently, in the https://github.com/pivotal/cloud-service-broker/search?q=read_write_endpoint_failover_policy&unscoped_q=read_write_endpoint_failover_policy  it appears the failover_policy is hard coded to automatic. We would like to be able to set it to manual so that we can control the failover.

**Describe the solution you'd like**
Have the failover_policy configurable so that we can change it from automatic to manual.

**Describe alternatives you've considered**
None

**Additional context**
We are currently using service_endpoints so we cannot reach the secondary database in the second Azure Location. So it a automatic failover occurs, our application then cannnot reach the database which in turn causes an outage on our side.

**Platform** 
Azure

**Applicable Services**
csb-azure-mssql-db-failover-group

**Comment by omerbensaadon** [comment]
I think this should be fixed with the delivery of https://github.com/pivotal/cloud-service-broker/commit/0ebfac6428c268e22d394f0f7fdaa68759be87f5

**Comment by drebake** [comment]
I tested and passing the "read_write_endpoint_failover_policy" = Manual value using the CLI works.

Is there a way I can add that to the server pair configuration in the config.yml file?

**Comment by omerbensaadon** [comment]
Do you want this configured globally or individually per failover group pair? 

Globally can be done today but per failover pair would be new functionality.

**Comment by drebake** [comment]
@omerbensaadon  I don't really have a current need to have it per failover pairs for the time being.... So an example on how to set it globally would be appreciated.

Thank!
