### ISSUE TITLE
[DOCS] Update example to connect to a db in a second fondation in documentation

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#58]
## Documentation Requested 

In the mssql-db-fog-config documentation, the example to connect from a second fondation to a existing bd needs to include the "instance_name" and "db_name".

URL:
https://github.com/pivotal/cloud-service-broker/blob/master/docs/mssql-db-fog-config.md

Section: 
"And then connect to that db in the second foundation:

Example:
cf create-service csb-azure-mssql-db-failover-group existing medium-fog -c '{"server_pair":"pair1"}'

Need's to change to:
cf create-service csb-azure-mssql-db-failover-group existing medium-fog -c '{"server_pair":"pair1","instance_name": "csb-failover-group-test", "db_name":"test-db"}'

**Comment by omerbensaadon** [comment]
Fixed!
