### ISSUE TITLE
[FR] Azure SQL DTU based plans

### ISSUE THREAD

**Issue by claassen** [pivotal/cloud-service-broker#65]
**Describe the solution you'd like**
Would like to be able to create Azure SQL database instances using DTU based plans (S0, S1 etc.)

**Describe alternatives you've considered**
None

**Priority**
High

**Priority Context**

**Platform** 
Azure

**Applicable Services**
csb-azure-mssql-db
csb-azure-mssql-db-failover-group

**Additional notes
I plan to work on this feature myself

**Comment by omerbensaadon** [comment]
Excited to receive your contribution here! Thanks @claassen

**Comment by erniebilling** [comment]
@claassen Are you looking for more support than is documented here - https://github.com/pivotal/cloud-service-broker/blob/master/docs/example-configs.md#config-file ?

**Comment by claassen** [comment]
@erniebilling Actually this is new to me, didn't realize you could configure plans via the config file. I'll try it out.

**Comment by claassen** [comment]
So it looks we are all good with just using the config file to define DTU based plans.
