### ISSUE TITLE
[BUG] template_ref should search paths relative to the build directory, not the working directory

### ISSUE THREAD

**Issue by mogul** [pivotal/cloud-service-broker#66]
## Description

The way `template_ref` is processed requires `$PWD` for the CSB invocation to be the same directory being built. CSB shouldn't require that!

## Expected Behavior
When you run `cloud-service-broker pak build /some/directory/name`, `template_ref` entries in `/some/directory/name/manifest.yml` will get resolved by searching in `/some/directory/name`.

## Actual Behavior
When you run `cloud-service-broker pak build /some/directory/name`, `template_ref` entries in `/some/directory/name/manifest.yml` fail to be resolved because the file is searched for in `$PWD`. You'll see something like this:

```
% build/cloud-service-broker.darwin pak build aws-brokerpak 
2020/08/17 22:12:39 Packing...
2020/08/17 22:12:39 Using temp directory: /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225
2020/08/17 22:12:39 Packing sources...
2020/08/17 22:12:39      https://github.com/hashicorp/terraform/archive/v0.12.23.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/src/terraform.zip
2020/08/17 22:12:43      https://github.com/terraform-providers/terraform-provider-aws/archive/v2.57.0.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/src/terraform-provider-aws.zip
2020/08/17 22:12:47      https://releases.hashicorp.com/terraform-provider-random/2.2.1/terraform-provider-random_2.2.1_linux_amd64.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/src/terraform-provider-random.zip
2020/08/17 22:12:48      https://releases.hashicorp.com/terraform-provider-mysql/1.9.0/terraform-provider-mysql_1.9.0_linux_amd64.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/src/terraform-provider-mysql.zip
2020/08/17 22:12:48      https://github.com/terraform-providers/terraform-provider-postgresql/archive/v1.5.0.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/src/terraform-provider-postgresql.zip
2020/08/17 22:12:50 Packing binaries...
2020/08/17 22:12:50      https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/bin/linux/amd64
2020/08/17 22:12:51      https://releases.hashicorp.com/terraform-provider-aws/2.57.0/terraform-provider-aws_2.57.0_linux_amd64.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/bin/linux/amd64
2020/08/17 22:12:54      https://releases.hashicorp.com/terraform-provider-random/2.2.1/terraform-provider-random_2.2.1_linux_amd64.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/bin/linux/amd64
2020/08/17 22:12:55      https://releases.hashicorp.com/terraform-provider-mysql/1.9.0/terraform-provider-mysql_1.9.0_linux_amd64.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/bin/linux/amd64
2020/08/17 22:12:56      https://releases.hashicorp.com/terraform-provider-postgresql/1.5.0/terraform-provider-postgresql_1.5.0_linux_amd64.zip -> /var/folders/p_/cydmjpbj3b5dzzl4pgzyy5br0000gn/T/brokerpak330015225/bin/linux/amd64
2020/08/17 22:12:57 Packing definitions...
2020/08/17 22:12:57 error while packing "aws-brokerpak": couldn't load provision template terraform/aws-rds-provision.tf: open terraform/aws-rds-provision.tf: no such file or directory
```

## Steps to Reproduce
1. Clone the `cloud-service-broker` repository.
2. `export USE_GO_CONTAINERS=true`
3. `make build`
4. `build/cloud-service-broker.darwin pak build aws-brokerpak` (for the Darwin build/OS situation, obviously)

## Context
This bug complicates delivering a brokerpak in a standalone repository. I'd like to use a single Docker image that can `pak init`, `pak build`, and `client run-examples`, but I have to awkwardly use the brokerpak source directory as the working directory, and it's hard to treat invocation of the Docker image the same way I would the CLI.

## Your Environment

* Version used: `master` as of the time of submitting this issue
* Operating System and version (desktop): OSX High Sierra
* Link to your project (if public): 
* Platform (Azure/AWS/GCP): N/A
* Applicable Services: N/A

**Comment by omerbensaadon** [comment]
Needs some further discussion with ENG... We triage M+W+F so will get back to you about this tomorrow

**Comment by omerbensaadon** [comment]
@mogul prioritized and in the backlog!

**Comment by mogul** [comment]
Thanks for the response! No rush, it's not blocking me.

**Comment by erniebilling** [comment]
Fixed in https://github.com/pivotal/cloud-service-broker/releases/tag/sb-0.1.0-rc.41-azure-0.0.1-rc.119
