### ISSUE TITLE
[FR] Support specifying minimum TLS version for Azure MySQL

### ISSUE THREAD

**Issue by claassen** [pivotal/cloud-service-broker#69]
**Is your feature request related to a problem? Please describe.**
No default TLS minimum version is configured when use_tls is set to true.

**Describe the solution you'd like**
Would like to be able to specify the minimum TLS version when creating Azure MySQL database.

**Describe alternatives you've considered**
N/A

**Priority**
High

**Priority Context**
Security requirement

**Platform** 
Azure

**Applicable Services**
MySQL

**Proposed Solution**
Use https://www.terraform.io/docs/providers/azurerm/r/mysql_server.html#ssl_minimal_tls_version_enforced

**Comment by omerbensaadon** [comment]
spoke with @claassen on Slack, he will submit a PR to fix this (thank you!)
