### ISSUE TITLE
[FR] Allow specifying Azure Redis max memory policy

### ISSUE THREAD

**Issue by claassen** [pivotal/cloud-service-broker#72]
**Is your feature request related to a problem? Please describe.**
Would like to be able to specify the max memory policy (e.g. allkeys-lru, noeviction) when creating Azure Redis service instances

**Describe the solution you'd like**
cf create-service csb-azure-redis small my-redis -c '{"maxmemory_policy": "value"}'

**Describe alternatives you've considered**
N/A

**Priority**
Low

**Platform** 
Azure

**Applicable Services**
Redis

**Comment by claassen** [comment]
Implemented by https://github.com/pivotal/cloud-service-broker/pull/73

**Comment by erniebilling** [comment]
Fixed
