### ISSUE TITLE
[BUG] Azure MySQL service creation fails with registration permission error when location is specified, even with skip_provider_registration set to true

### ISSUE THREAD

**Issue by claassen** [pivotal/cloud-service-broker#76]
## Description
When creating an Azure MySQL service instance with skip_provider_registration set to true the service creation is successful, however when also specifying location as "eastus" it fails with registration permission issues even though skip_provider_registration is still set to true.

## Expected Behavior
Service instance should be created successfully

## Actual Behavior
Service instance fails with error:

Error: Error ensuring Resource Providers are registered.Terraform automatically attempts to register the Resource Providers it supports toensure it's able to provision resources.If you don't have permission to register Resource Providers you may wish to use
           the"skip_provider_registration" flag in the Provider block to disable this functionality.Please note that if you opt out of Resource Provider Registration and Terraform triesto provision a resource from a Resource Provider which is unregistered, then the
           errorsmay appear misleading - for example:> API version 2019-XX-XX was not found for Microsoft.FooCould indicate either that the Resource Provider "Microsoft.Foo" requires registration,but this could also indicate that this Azure Region doesn't support this API
           version.More information on the "skip_provider_registration" flag can be found here:https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registrationOriginal Error: Cannot register provider Microsoft.CustomProviders with Azure Resource
           Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'b56542ac-6ea5-48d4-849a-4cf7a8285032' with object
           id 'b56542ac-6ea5-48d4-849a-4cf7a8285032' does not have authorization to perform action 'Microsoft.CustomProviders/register/action' over scope '/subscriptions/957108b5-005f-4b11-bae1-9e62ba39e857' or the scope is invalid. If access was recently granted, please
           refresh your credentials.".  on brokertemplate/definition.tf line 33, in provider "azurerm":  33: provider "azurerm" { exit status 1

## Possible Fix
N/A

## Steps to Reproduce
Broker configuration:

```yaml
csb-azure-mysql:
    provision:
      defaults: '{
       "skip_provider_registration": true,
       "resource_group":"mfc-use-pcf-psb",
       "location", "eastus"
      }'
```

2. cf create-service csb-azure-mysql small test-csb-mysql-eastus

## Context
Related to https://github.com/pivotal/cloud-service-broker/issues/68. When using the authorized_network parameter to add VNET access rules I had to also specify the location as "eastus" to match the location where our VNET is and ran into this error. I then tried removing the authorized_network parameter and just specifying the location as "eastus" and still got the same error.

## Your Environment
* Version used: sb-0.1.0-rc.47-azure-0.0.1-rc.126
* Platform (Azure/AWS/GCP): Azure
* Applicable Services: MySQL

**Comment by claassen** [comment]
So I ran this a few more times and am actually getting different error messages in some cases that don't seem to make any sense:

Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client 'b56542ac-6ea5-48d4-849a-4cf7a8285032' with object id 'b56542ac-6ea5-48d4-849a-4cf7a8285032' does not have authorization to perform action 'Microsoft.MachineLearningServices/register/action' over scope '/subscriptions/957108b5-005f-4b11-bae1-9e62ba39e857' or the scope is invalid. If access was recently granted, please refresh your credentials.

**Comment by erniebilling** [comment]
We're looking in to this.

**Comment by claassen** [comment]
Interestingly even with "location" set to the default value of "westus", just the fact that it is specified seems to cause this issue. E.g.:

Fails:

```
csb-azure-mysql:
    provision:
      defaults: '{
       "skip_provider_registration": true,
       "resource_group":"MFC-USE-PCF-PSB",
       "location", "westus"
      }'
```

Works:

```
csb-azure-mysql:
    provision:
      defaults: '{
       "skip_provider_registration": true,
       "resource_group":"MFC-USE-PCF-PSB",
      }'
```

**Comment by claassen** [comment]
Also if I change the default location in the brokerpak from westus to eastus and rebuild, it works fine and works with the authorized_network configuration as well.

**Comment by erniebilling** [comment]
Thanks for sharing this @claassen, it will help us diagnose the problem.

**Comment by erniebilling** [comment]
@claassen I think I see the problem:

```
csb-azure-mysql:
    provision:
      defaults: '{
       "skip_provider_registration": true,
       "resource_group":"MFC-USE-PCF-PSB",
       "location", "westus"
      }'
```

`"location", "westus"` should be `"location":"westus"`

I'll bet the json parsing is failing silently here and the whole config is being thrown out, thus resulting in the `skip_provider_registration` being ignored.

I'll make sure that this results in some logging that points to the issue.
