### ISSUE TITLE
[FR] consider terraform-provider-credhub for credhub support

### ISSUE THREAD

**Issue by gberche-orange** [pivotal/cloud-service-broker#80]
Looking at the roadmap, I see mention of credhub at https://trello.com/c/GIqjXnP8/53-credhub-integration and wonder use of https://github.com/orange-cloudfoundry/terraform-provider-credhub provider was considered, or whether additional details could be shared on the scope of this roadmap element (the trello card does not provide much details)

Any chance to open the trello board to comments from the community ?

**Comment by omerbensaadon** [comment]
@gberche-orange thanks for your input! I'll make sure ENG gets back to you on this, they are on West Coast hours so won't be for a little while 

Commenting has now been enabled on the Trello cards! Thanks for the feedback. 

PS: have you joined the [#cloudservicebroker-beta](https://cloudfoundry.slack.com/archives/C0164KKEZGX) channel on the [Cloud Foundry Slack](https://slack.cloudfoundry.org/)?

**Comment by erniebilling** [comment]
@gberche-orange Broker credhub support was built in to the broker golang code so all brokerpaks could get the proper CAPI required support and each brokerpak would not have to duplicate the work. The credhub provider could very well be useful in other situations and is on our radar should the need arise.

**Comment by gberche-orange** [comment]
I now understand that credhub support actually refers to service binding credential returning credhub-ref. Submitted https://github.com/pivotal/cloud-service-broker/pull/89 doc clarification.

Can you please confirm that configuring the credhub variables will automatically turn returned binding credentials credhub references for all served brokerpacks (i.e. that there is no other opt-in in the brokerpak specs ) ?

**Comment by erniebilling** [comment]
I can confirm that once credhub is configured for the broker, all brokerpak binding information will be put in credhub.
