### ISSUE TITLE
[BUG] Cloud service broker tile 0.0.28-azure-beta no stemcell associated

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#86]
## Description
We were able to successfully install the Beta cloud service broker tile manually using the opsman but when we try to deploy using platform automation, we get an error since no stemcell are specified in the release.

## Expected Behavior
A stemcell is specified in pivnet to download so that the  errands to be able to run sucessfully.

## Actual Behavior
When running the paltform automation, an error occurs when trying to get the information on the stemcell required. No stemcell specified in the "download-product" section.
[](https://network.pivotal.io/products/cloud-service-broker/)
![CSB-0 0 28-azure-platform-automation](https://user-images.githubusercontent.com/47528848/93104331-b4072980-f67b-11ea-977e-a5c7c5cae702.png)

## Possible Fix
- Add a dependancy on a stemcell as a  "download-product" to the release so that the platform automation tools are able to download the proper stemcell and run trough other steps of the deployments.

- We can change our paltform automation pipeline so that it bypass the step in order to download the stemcell if no stemcell will be specified for this tile in the "download-product" section.

## Steps to Reproduce
1. Use platform automation pipeline in order to install the current Azure 0.0.28 beta release.

## Context
We are able to install the tile manually but not able to use platform automation in order to perform update/upgrades.

## Your Environment

* Version used: Cloud service broker for Microsoft Azure 0.0.28
* Platform (Azure/AWS/GCP): Azure
* Applicable Services:  Bosh 2.10.1 TAS: 2.10.3

**Comment by erniebilling** [comment]
@drebake The broker has no stemcell requirement as the default for the platform is sufficient. If you can fix your pipeline to skip stemcell install if none is specified, you should be in good shape.

**Comment by drebake** [comment]
Thanks @erniebilling for once again a quick prompt response! 

We wanted to confirm that this was the case. before adapting our pipeline for this situation.

**Comment by thanhdesjardins** [comment]
Hello @erniebilling ,

All the Vmware/Pivotal tiles have a stemcell associated on Pivnet.
For example, the tile Spring cloud services only deploys an app on PCF (like Cloud Service Borker) but if you check the tile on pivnet, you can see that a stemcell is associated.

I think it's better to have the same thing for Cloud Service Broker as well.

Could you please add the stemcell on the pivnet page?

**Comment by omerbensaadon** [comment]
we're on it! It's being worked now

**Comment by thanhdesjardins** [comment]
Great news @omerbensaadon :)
Do you know when the pivnet page will be updated? We will be able to test our pipeline like this.

**Comment by omerbensaadon** [comment]
https://network.pivotal.io/products/cloud-service-broker

Check now! 0.0.34-azure-beta should do it for you

**Comment by thanhdesjardins** [comment]
Hello @omerbensaadon ,

I just tried and I still have the same problem.

![image](https://user-images.githubusercontent.com/54329071/93232001-65bf5c80-f747-11ea-8806-cbe8271de925.png)


If you check the page on pivnet, we still don't see the stemcell:

![image](https://user-images.githubusercontent.com/54329071/93232100-812a6780-f747-11ea-9741-e77e8fc6d7f4.png)


If you compare with Spring cloud service:

![image](https://user-images.githubusercontent.com/54329071/93232230-a919cb00-f747-11ea-8a4c-12d74e4d74ae.png)

**Comment by erniebilling** [comment]
@thanhdesjardins So that I can fully validate the change - what tool/CLI does your pipeline use determine the stemcell requirement for the tile? I've added the metadata to the tile.yml and the `tile-generator` spits out stemcell info, so I'm a little lost. I'll confer with the tile-generator team to see if I'm missing something.

```
name: cloud-service-broker-azure
label: Cloud Service Broker for Microsoft Azure
description: A cloud service broker for Microsoft Azure services
version: 0.0.34
sha1: False
stemcell: ubuntu-xenial 621
```

**Comment by thanhdesjardins** [comment]
@erniebilling ,

We use the task download-product from platform automation toolkit:

https://docs.pivotal.io/platform-automation/v5.0/tasks.html#download-product

In the config file for the task we specify that the latest stemcell available for this tile is downloaded.
We have a generic code for all the tiles and modifying the workflow will make us creating a dedicated pipeline.

In fact I'm just asking for the stemcell to be available on the product page. (like the other tiles in fact)

Here is an example:

![image](https://user-images.githubusercontent.com/54329071/93248792-5992c980-f75e-11ea-8a86-24bc65b55d86.png)

I guess you can ask the tile-generator team for this.

**Comment by erniebilling** [comment]
@thanhdesjardins Thanks, this helps. This is pulling information from Pivnet metadata, not out of the tile. We'll get this added to the Pivnet metadata.

**Comment by thanhdesjardins** [comment]
@erniebilling ,

Thanks.
do you know when it will be available on pivnet metadata?

**Comment by erniebilling** [comment]
Working on it right now.

**Comment by omerbensaadon** [comment]
@thanhdesjardins @drebake should be fixed now?

**Comment by thanhdesjardins** [comment]
@erniebilling , yes it works now.
Thanks for the quick fix!
