### ISSUE TITLE
[BUG] Tile version of the Cloud Service Broker doesn't store csb-azure-storage-account credentials in CredHub.

### ISSUE THREAD

**Issue by drebake** [pivotal/cloud-service-broker#95]
## Description
When creating a csb-azure-storage-account service, the credentials are not stored in the CredHub like other services. Access_keys and storage_account_name are available in the VCAP_SERVICES. I recall this not being the case with the Credhub information in the previous non-tile version of the broker.

## Expected Behavior
Binding information should be stored in the Credhub.

## Actual Behavior
Access_keys and storage_account_name available in the VCAP_SERVICES

## Possible Fix
Store the binding information in the credhub like other services.

## Steps to Reproduce
1. Install tile version of the broker
2. cf created-service  csb-azure-storage-account
3. cf bind to a application
4. cf env application_name

## Context
Upon testing recent PR for csb-azure-storage-account changes, we noticed that the default behaviour of storing binding information in the credhub does not behave like other services.

## Your Environment
Version used: Cloud service broker for Microsoft Azure 0.0.35
Platform (Azure/AWS/GCP): Azure
Applicable Services: Bosh 2.10.1 TAS: 2.10.3

**Comment by drebake** [comment]
I realized that while we were testing the authorized_networks fix, the actual broker that didn't put the credentials in the credhub was the broker that we had built. I switched back to the broker provided by the tile and no credhub issues with that version.

**Comment by omerbensaadon** [comment]
@erniebilling @svennela heads up!
